### ISSUE TITLE
Issues használata

### ISSUE THREAD

**Issue by szepbalazs06** [gtportal/w3suli#1]
Nagyon hasznosnak tűnik ez a lehetőség, ha a többiek is lesznek GitHub-on érdemes lesz használni @gtportal

**Comment by gtportal** [comment]
Kedves Balázs,
köszönöm az ötletet! 
Mivel nyilvánosan elérhetők a hozzászollások, így ezt a felületet használhatjuk a munka összehangolására, feladatok nyílvántatására és a csoporton belüli kapcsolattartásra is.
Az általad készített morzsanavigációt teszteltem. Jól működik.
Gondolom a lábléc kódjával gyorsan megleszel. Csütörtökön megbeszéljük a következő feladatot.

**Comment by gtportal** [comment]
Gellért megvalósította az alapbeállítások kezelését, így már dinamikusan tudunk váltani a stíluslapok között.
Kérem, hogy a stíluslapok készítői már saját fájlnevet használjanak, így könnyebb lesz összefésülni a műveket.
Fájlnevek kiosztása:
w3suli_stilus_0.css - Bárczi Dávid 
w3suli_stilus_1.css - Beschenbacher Kornél
w3suli_stilus_2.css - Guti Patrik
w3suli_stilus_3.css - Hegedüs Erik
w3suli_stilus_4.css - Nagy Gábor
w3suli_stilus_5.css - Pallagi Dániel
w3suli_stilus_6.css - Parma Robin
w3suli_stilus_7.css - Répás Benedek
w3suli_stilus_8.css - Szabó Máté
w3suli_stilus_9.css - Varga Krisztián
Megj. A tesztelésre használt HTML fájlokban is át kell írni a Link elemek href paramétereit!
