### ISSUE TITLE
Új felhasználó felvétele 

### ISSUE THREAD

**Issue by gtportal** [gtportal/w3suli#3]
Készíti: Tóth-Kovács Gellért
Módosítandó: Felhasznalo.php
Kérés: Csak ezt a fájlt módosítsd! Ha elkészül, akkor töltsd fel a drive-ra, a saját könyvtáradba.
Megj. ezen a fájlon más is dolgozik.

**Comment by tkgellert** [comment]
A regisztráció sikeresen elkészült. Megtekinthető a Drive-on.
