### ISSUE TITLE
Bejelentkezés 1.

### ISSUE THREAD

**Issue by gtportal** [gtportal/w3suli#4]
Feladat: Bejelentkezés űrlap elkészítése
Készíti: Wigmond Ádám
Módosítandó: Felhasznalo.php
Kérés: Csak ezt a fájlt módosítsd! Ha elkészül, akkor töltsd fel a drive-ra, a saját könyvtáradba.
Megj. ezen a fájlon más is dolgozik.

**Comment by tkgellert** [comment]
A bejelentkezést és kijelentkezést elkészítettem.
